### ISSUE TITLE
ExpectRuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'mask'ed object of backend CUDA but got backend CPU for argument #2 'mask'

### ISSUE THREAD

**Issue by MiaoXiong2320** [deepnlp-cs599-usc/quac#3]
## Issue description
I have deleted the Bert part of this code and try to run the code with only flow-attention part reserved, but I got this error as follows.

`ExpectRuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'mask'ed object of backend CUDA but got backend CPU for argument #2 'mask'`

I am not sure where is wrong and whether this version of code can work. I didn't change any code related flow attention.

So I just want to know whether you have met this error.

`Traceback (most recent call last):
  File "train_QuAC.py", line 341, in <module>
    main()
  File "train_QuAC.py", line 220, in main
    model.update(batch)
  File "/QA_model/model_QuAC.py", line 90, in update
    score_s, score_e, score_no_answ = self.network(*inputs)
  File "anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "QA_model/detail_model.py", line 348, in forward
    doc_hiddens_flow = flow_operation(doc_hiddens, self.dialog_flow1, attn = self.flow_attn1)
  File "/home/ai/Documents/code_non_bert/QA_model/detail_model.py", line 328, in flow_operation
    attentive_flow_out = attn(flow_out)
  File "anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "Documents/code_non_bert/QA_model/layers.py", line 355, in forward
    scores.data.masked_fill_(x_mask.data, -float("inf"))
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'mask'`

**Comment by rohitmujumdar** [comment]
Hi Emma, were you able to resolve this? Also how did you delete the BERT part of this to only run Attention?
